<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\AVMatrixStudio.ico</ApplicationIcon>
    <AssemblyName>AVMatrixStudio</AssemblyName>
    <RootNamespace>AVMatrixStudio</RootNamespace>
    <Version>4.0.0</Version>
    <Authors>InN8 Labs</Authors>
    <Copyright>Copyright © 2026 InN8 Labs</Copyright>
    <Product>AV Matrix Studio</Product>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\AVMatrixStudio.ico"
                      LogicalName="AVMatrixStudio.Assets.AVMatrixStudio.ico" />
    <EmbeddedResource Include="Assets\AVMatrixStudioLogo.png"
                      LogicalName="AVMatrixStudio.Assets.AVMatrixStudioLogo.png" />
    <EmbeddedResource Include="Assets\InN8LabsMascot.png"
                      LogicalName="AVMatrixStudio.Assets.InN8LabsMascot.png" />
    <EmbeddedResource Include="Assets\N8LogoDark.png"
                      LogicalName="AVMatrixStudio.Assets.N8LogoDark.png" />
    <EmbeddedResource Include="Assets\N8LogoLight.png"
                      LogicalName="AVMatrixStudio.Assets.N8LogoLight.png" />
    <None Update="README-RUN.txt"
          CopyToPublishDirectory="PreserveNewest"
          ExcludeFromSingleFile="true" />
  </ItemGroup>
</Project>
